<?php

$lang_admin_maintenance = array(

'Maintenance head' => 'Mantenimiento del foro',
'Rebuild index subhead' => 'Reconstruir el índice de búsqueda',
'Rebuild index info' => 'Si has agregado, editado o quitado publicaciones manualmente en la base de datos o si tienes problemas buscando, deberías reconstruir el índice de búsqueda. Para un mejor desempeño, deberías poner el foro en %s durante la reconstrucción. <strong>¡El reconstruir el índice de búsqueda puede tomar mucho tiempo e incrementará la carga del servidor durante el proceso de reconstrucción!</strong>',
'Posts per cycle label' => 'Publicaciones por ciclo',
'Posts per cycle help' => 'El número de publicaciones a procesar por página. Ej. si fueras a ingresar 300, se procesarían trescientas publicaciones y entonces la página se refrescaría. Esto sirve para prevenir que el <i>script</i> tenga tiempo de espera agotado durante el proceso de reconstrucción.',
'Starting post label' => 'ID de publicación inicial',
'Starting post help' => 'El ID de la publicación en la cual comenzar la reconstrucción. El valor predeterminado es el primero disponible en la base de datos. Normalmente, no querrías cambiar esto.',
'Empty index label' => 'Índice vacío',
'Empty index help' => 'Selecciona esto si quieres que se vacíe el índice de búsqueda antes de reconstruir (ve más abajo).',
'Rebuild completed info' => 'Once the process has completed, you will be redirected back to this page. If you are forced to abort the rebuild process, make a note of the last processed post ID and enter that ID+1 in "Starting post ID" when/if you want to continue ("Empty index" must not be selected).',
'Rebuild index' => 'Reconstruir el índice',
'Rebuilding search index' => 'Reconstruyendo los índices de búsqueda',
'Rebuilding index info' => 'Reconstruyendo el índice. Este podría ser un buen momento para prepararte un café. :-)',
'Processing post' => 'Procesando la publicación <strong>%s</strong>…',
'Click here' => 'Haz clic aquí',
'Javascript redirect failed' => 'No funcionó la redirección automática. %s para continuar…',
'Posts must be integer message' => 'Las publicaciones por ciclo deben tener un valor entero positivo.',
'Days must be integer message' => 'Los días para reducir deben tener un valor entero positivo.',
'No old topics message' => 'There are no topics that are %s days old. Please decrease the value of "Days old" and try again.',
'Posts pruned redirect' => 'Publicaciones reducidas. Redirigiendo…',
'Prune head' => 'Reducir',
'Prune subhead' => 'Reducir las publicaciones antiguas',
'Days old label' => 'Días',
'Days old help' => 'The number of days "old" a topic must be to be pruned. E.g. if you were to enter 30, every topic that didn\'t contain a post dated less than 30 days old would be deleted.',
'Prune sticky label' => 'Reducir los temas pegados',
'Prune sticky help' => 'Cuando se habilita, los temas pegados también se reducirán.',
'Prune from label' => 'Reducir de este foro',
'All forums' => 'Todos los foros',
'Prune from help' => 'El foro desde el cual quieres reducir publicaciones.',
'Prune info' => 'Usa esta característica con cuidado. <strong>Las publicaciones reducidas nunca se pueden recuperar.</strong> Para mejor desempeño, deberías poner el foro en %s durante la reducción.',
'Confirm prune subhead' => 'Confirma la reducción de publicaciones',
'Confirm prune info' => '¿Estás seguro de querer reducir todos los temas que tienen más de %s días de %s (%s temas).',
'Confirm prune warn' => '¡ADVERTENCIA! El reducir publicaciones, las elimina permanentemente.',

);