<?php

$lang_admin_common = array(

'Admin menu' => 'Menú de administración',
'Plugins menu' => 'Menú de extensiones',
'Moderator menu' => 'Menú del moderador',
'Index' => 'Índice',
'Categories' => 'Categorías',
'Forums' => 'Foros',
'Users' => 'Usuarios',
'User groups' => 'Grupos de usuarios',
'Options' => 'Opciones',
'Permissions' => 'Permisos',
'Censoring' => 'Censura',
'Bans' => 'Vetos',
'Prune' => 'Reducir',
'Maintenance' => 'Mantenimiento',
'Reports' => 'Informes',
'Server statistics' => 'Estadísticas del servidor',
'Admin' => 'Administración',
'Go back' => 'Volver',
'Delete' => 'Eliminar',
'Update' => 'Actualizar',
'Add' => 'Agregar',
'Edit' => 'Editar',
'Remove' => 'Quitar',
'Yes' => 'Sí',
'No' => 'No',
'Save changes' => 'Guardar los cambios',
'Save' => 'Guardar',
'here' => 'aquí',
'Action' => 'Acción',
'None' => 'Ninguno',
'Maintenance mode' => 'modo de mantenimiento',
'No plugin message' => 'No hay extensión llamada %s en el directorio de extensiones.',
'Plugin failed message' => 'La carga de la extensión - <strong>%s</strong> - falló.',

);