<?php

$lang_admin_forums = array(

'Forum added redirect' => 'Foro agregado. Redirigiendo…',
'Forum deleted redirect' => 'Foro eliminado. Redirigiendo…',
'Forums updated redirect' => 'Foros actualizados. Redirigiendo…',
'Forum updated redirect' => 'Foro actualizado. Redirigiendo…',
'Perms reverted redirect' => 'Permisos revertidos a sus predeterminados. Redirigiendo…',
'Must enter name message' => 'Debes ingresar el nombre de un foro.',
'Must be integer message' => 'La posición debe tener un valor entero positivo.',
'New forum' => 'Nuevo foro',
'Add forum head' => 'Agregar foro',
'Create new subhead' => 'Crear un nuevo foro',
'Add forum label' => 'Agregar el foro a la categoría',
'Add forum help' => 'Seleccionar la categoría para la cual deseas agregar un nuevo foro.',
'Add forum' => 'Agregar foro',
'No categories exist' => 'No existen categorías',
'Edit forums head' => 'Editar foros',
'Category subhead' => 'Categoría:',
'Forum label' => 'Foro',
'Edit link' => 'Editar',
'Delete link' => 'Eliminar',
'Position label' => 'Posición',
'Update positions' => 'Actualizar posiciones',
'Confirm delete head' => 'Confirma la eliminación del foro',
'Confirm delete subhead' => '¡Importante! Lee antes de eliminar',
'Confirm delete info' => '¿Estás seguro de que quieres eliminar el foro <strong>%s</strong>?',
'Confirm delete warn' => '¡ADVERTENCIA! ¡Al eliminar un foro, se eliminarán las publicaciones (si hay alguna) en ese foro!',
'Edit forum head' => 'Editar foro',
'Edit details subhead' => 'Editar los detalles del foro',
'Forum name label' => 'Nombre del foro',
'Forum description label' => 'Descripción (HTML)',
'Category label' => 'Categoría',
'Sort by label' => 'Ordenar temas por',
'Last post' => 'Última publicación',
'Topic start' => 'Inicio del tema',
'Subject' => 'Asunto',
'Redirect label' => 'URL de redirección',
'Redirect help' => 'Solo disponible en foros vacíos',
'Group permissions subhead' => 'Editar los permisos del grupo para este foro',
'Group permissions info' => 'In this form, you can set the forum specific permissions for the different user groups. If you haven\'t made any changes to this forum\'s group permissions, what you see below is the default based on settings in %s. Administrators always have full permissions and are thus excluded. Permission settings that differ from the default permissions for the user group are marked red. The "Read forum" permission checkbox will be disabled if the group in question lacks the "Read board" permission. For redirect forums, only the "Read forum" permission is editable.',
'Read forum label' => 'Leer foro',
'Post replies label' => 'Publicar respuestas',
'Post topics label' => 'Publicar temas',
'Revert to default' => 'Revertir al predeterminado',

);