<?php

$lang_admin_permissions = array(

'Perms updated redirect' => 'Permisos actualizados. Redirigiendo…',
'Permissions head' => 'Permisos',
'Posting subhead' => 'Publicando',
'BBCode label' => 'CódigoBB',
'BBCode help' => 'Permitir CódigoBB en las publicaciones (recomendado).',
'Image tag label' => 'Etiqueta de imagen',
'Image tag help' => 'Permitir la etiqueta de CódigoBB [img][/img] en las publicaciones.',
'All caps message label' => 'Mensaje en mayúsculas',
'All caps message help' => 'Permitir que un mensaje contenga solo mayúsculas.',
'All caps subject label' => 'Asunto en mayúsculas',
'All caps subject help' => 'Permitir que un asunto contenga solamente mayúsculas.',
'Require e-mail label' => 'Requerir el correo electrónico del invitado',
'Require e-mail help' => 'Requerir que los invitados entreguen una dirección de correo electrónico al publicar.',
'Signatures subhead' => 'Firmas',
'BBCode sigs label' => 'CódigoBB en firmas',
'BBCode sigs help' => 'Permitir CódigoBB en las firmas de los usuarios.',
'Image tag sigs label' => 'Etiquetas de imagen en las firmas',
'Image tag sigs help' => 'Permitir la etiqueta de CódigoBB [img][/img] en las firmas de los usuarios (no se recomienda).',
'All caps sigs label' => 'Firma en mayúsculas',
'All caps sigs help' => 'Permitir una firma que contenga solo mayúsculas.',
'Max sig length label' => 'Largo máximo de la firma',
'Max sig length help' => 'El número máximo de caracteres que puede contener una firma de usuario.',
'Max sig lines label' => 'Máximo de lineas en las firmas',
'Max sig lines help' => 'El número máximo de líneas que una firma de usuario puede contener.',
'Registration subhead' => 'Registro',
'Banned e-mail label' => 'Permitir direcciones de correo electrónico vetadas',
'Banned e-mail help' => 'Permitir que los usuarios se registren o cambien a una dirección de correo electrónico o dominio vetado. Si se deja en su configuración predetermnada (sí), esta acción se permitirá, pero un correo electrónico de alerta se enviará a la lista de correo (una forma efectiva para detectar múltiples registros).',
'Duplicate e-mail label' => 'Permitir direcciones de correo electrónico duplicadas',
'Duplicate e-mail help' => 'Controla si los usuarios deberían poder registrarse con una dirección de correo electrónico que otro usuario ya tiene. Si se permite, un correo electrónico de alerta se enviará a la lista de correo si se detecta un duplicado.',

);