<?php

$lang_help = array(

'Help' => 'Ayuda',
'produces' => 'produce',
'BBCode' => 'CódigoBB',
'BBCode info 1' => 'El CódigoBB es una colección de etiquetas de formato que se usan para cambiar la apariencia del texto en este foro. El CódigoBB está basado en el mismo principio, y es muy similar al HTML. Más abajo hay una lista de cada CódigoBB e instrucciones sobre cómo usarlos.',
'BBCode info 2' => 'Los administradores tienen la habilidad de habilitar o deshabilitar el CódigoBB. Puedes decir si el CódigoBB está habilitado o deshabilitado en el margen izquierdo cada vez que publiques un mensaje o edites tu firma.',
'Text style' => 'Estilo del texto',
'Text style info' => 'Las siguientes etiquetas cambian la apariencia del texto:',
'Bold text' => 'Texto en negrita',
'Underlined text' => 'Texto subrayado',
'Italic text' => 'Texto en cursiva',
'Strike-through text' => 'Texto tachado',
'Red text' => 'Texto rojo',
'Blue text' => 'Texto azul',
'Heading text' => 'Texto de cabecera',
'Deleted text' => 'Texto eliminado',
'Inserted text' => 'Texto insertado',
'Emphasised text' => 'Texto destacado',
'Links and images' => 'Enlaces e imágenes',
'Links info' => 'Puedes crear enlaces a otros documentos o a direcciones de correo electrónico, usando las siguientes etiquetas:',
'This help page' => 'Esta página de ayuda',
'My email address' => 'Mi dirección de correo electrónico',
'Images info' => 'If you want to display an image you can use the img tag. The text appearing after the "=" sign in the opening tag is used for the alt attribute and should be included whenever possible.',
'FluxBB bbcode test' => 'Prueba de CódigoBB de FluxBB',
'Test topic' => 'Tema de prueba',
'Test post' => 'Publicación de prueba',
'Test forum' => 'Foro de prueba',
'Test user' => 'Usuario de prueba',
'Quotes' => 'Citas',
'Quotes info' => 'Si quieres citar a alguien, deberías usar la etiqueta de citas.',
'Quotes info 2' => 'Si no quieres citar a alguien en particular, puedes usar la etiqueta de cita sin especificar un nombre.',
'Quote text' => 'Este es el texto que quiero citar.',
'produces quote box' => 'produce un cuadro de cita como este:',
'quote note' => 'Nota: Si un nombre de usuario contiene los caracteres [ o ], puedes escribirlo entre comillas.',
'Code' => 'Código',
'Code info' => 'Cuando muestras código fuente, deberías asegurarte de que usas la etiqueta de código. El texto desplegado con la etiqueta de código, usará un tipo de letra monoespaciado y no será afectado por otras etiquetas.',
'Code text' => 'Esto es algo de código.',
'produces code box' => 'produce una caja de código así:',
'Nested tags' => 'Etiquetas anidadas',
'Nested tags info' => 'El CódigoBB puede anidarse para crear formato más avanzado. Por ejemplo:',
'Bold, underlined text' => 'Texto en negrita, subrayado',
'Lists' => 'Listas',
'List info' => 'Para crear una lista, puedes usar la etiqueta de lista. Puedes crear 3 tipos de listas usando la etiqueta de lista.',
'List text 1' => 'Ítem 1 de la lista de ejemplo.',
'List text 2' => 'Ítem 2 de la lista de ejemplo.',
'List text 3' => 'Ítem 3 de la lista de ejemplo.',
'produces list' => 'produce una lista con viñetas.',
'produces decimal list' => 'produce una lista numerada.',
'produces alpha list' => 'produce una lista alfabéticamente etiquetada.',
'Smilies' => 'Emoticones',
'Smilies info' => 'Si quieres (y si está habilitado), el foro puede convertir una serie de emoticones a representaciones en imágenes de esos emoticones. Este foro reconoce los siguientes emoticones y los reemplaza con imágenes.',

);